name: Auto Merge Pull Requests

on:
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
    - name: Auto-merge Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          // Merge script
          console.log("MERGING THE PULL REQUEST")
      # - name: Auto-merge pull request
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const pullRequest = context.payload.check_suite.pull_requests[0];
      #       const { owner, repo } = context.repo;
      #       const pull_number = pullRequest.number;

      #       await github.pulls.merge({
      #         owner,
      #         repo,
      #         pull_number,
      #         merge_method: 'squash', // You can use 'merge', 'squash', or 'rebase'
      #       });
      # - name: Prebuild and push
      #   uses: ${{ github.repo }}/.github/workflows/prebuild.yml@main
