name: Auto Merge Pull Requests

on:
  workflow_dispatch:
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    # if: >
    #   github.event.check_suite.conclusion == 'success' &&
    #   github.event.check_suite.pull_requests != null &&
    #   github.event.check_suite.pull_requests[0].base.ref == 'main'
    runs-on: ubuntu-latest
    env:
      CH_ST: ${{ toJson(github.event.check_suite) }}
    steps:
    - name: Auto-merge Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          // Merge script
          console.log("MERGING THE PULL REQUEST, NICEEEEEEEEEEEEEEE")
      # - name: Auto-merge pull request
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const pullRequest = context.payload.check_suite.pull_requests[0];
      #       const { owner, repo } = context.repo;
      #       const pull_number = pullRequest.number;

      #       await github.pulls.merge({
      #         owner,
      #         repo,
      #         pull_number,
      #         merge_method: 'squash', // You can use 'merge', 'squash', or 'rebase'
      #       });
      # - name: Prebuild and push
      #   uses: ${{ github.repo }}/.github/workflows/prebuild.yml@main
