name: Dev Containers Prebuild

on:
  workflow_call:
    inputs:
      compose_file:
        description: "The path to docker compose file"
        type: string
        required: true
        default: "docker-compose.dev.yml"
      dockerfile:
        description: "The dockerfile path"
        type: string
        required: true
        default: "Dockerfile.dev"
      push_registry:
        description: "Push the container to the container registry"
        type: boolean
        required: false
        default: false
      
  pull_request:
    branches: main
    paths:
      - "package*.json"
  workflow_dispatch:
    inputs:
      compose_file:
        description: "The path to docker compose file"
        type: string
        required: true
        default: "docker-compose.dev.yml"
      dockerfile:
        description: "The dockerfile path"
        type: string
        required: true
        default: "Dockerfile.dev"

permissions:
  contents: read
  packages: write
  pull-requests: read

env:
  DOCKERFILE: ${{ inputs.dockerfile || 'Dockerfile.dev' }}
  COMPOSE_FILE: ${{ inputs.compose_file || 'docker-compose.dev.yml' }}
  GH_TK: ${{ secrets.GITHUB_TOKEN }}
  PS_RG: ${{ inputs.push_registry || false }}

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Set Repository name
        run: echo "GH_RP=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Get package version
        id: bump_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ env.GH_TK }}
          release_branches: main
          dry_run: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ env.GH_TK }}

      - name: Build and export
        uses: docker/build-push-action@v6.7.0
        with:
          file: ${{ env.DOCKERFILE }}
          sbom: true
          push: ${{ env.PS_RG }}
          tags: |
            ghcr.io/${{ env.GH_RP }}:${{ github.sha }}
            ghcr.io/${{ env.GH_RP }}:${{ steps.bump_version.outputs.new_tag }}
            ghcr.io/${{ env.GH_RP }}:dev-latest
          cache-from: type=registry,ref=ghcr.io/${{ env.GH_RP }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.GH_RP }}:buildcache,mode=min

      - name: Cleanup
        run: |
          docker system prune -a -f
          docker builder prune -a -f
          echo 'SUCCESS=true' >> $GITHUB_OUTPUT
